# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0003_auto_20160513_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='proglam',
            name='parent',
        ),
        migrations.AlterField(
            model_name='function',
            name='git',
            field=models.CharField(blank=True, max_length=255, verbose_name='git'),
        ),
        migrations.AlterField(
            model_name='function',
            name='mightiness',
            field=models.CharField(max_length=255, verbose_name='kinou'),
        ),
        migrations.AlterField(
            model_name='function',
            name='tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='pkg',
            name='child',
            field=models.CharField(blank=True, max_length=255, verbose_name='ko'),
        ),
        migrations.AlterField(
            model_name='pkg',
            name='git',
            field=models.CharField(blank=True, max_length=255, verbose_name='git'),
        ),
        migrations.AlterField(
            model_name='pkg',
            name='mightiness',
            field=models.CharField(max_length=255, verbose_name='kinou'),
        ),
        migrations.AlterField(
            model_name='pkg',
            name='tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='child',
            field=models.CharField(blank=True, max_length=255, verbose_name='ko'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='git',
            field=models.CharField(blank=True, max_length=255, verbose_name='git'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglam', to='data_base.Pkg', verbose_name='pkg'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='mightiness',
            field=models.CharField(max_length=255, verbose_name='kinou'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='tag',
            field=models.CharField(blank=True, max_length=255, verbose_name='tag'),
        ),
    ]
