# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0007_auto_20160513_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='data_base.Proglam', verbose_name='proglam'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglams', to='data_base.Pkg', verbose_name='pkg'),
        ),
    ]
