# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0008_auto_20160515_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='mightiness',
            field=models.TextField(max_length=255, verbose_name='kinou'),
        ),
        migrations.AlterField(
            model_name='pkg',
            name='mightiness',
            field=models.TextField(max_length=255, verbose_name='kinou'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglams', to='data_base.Pkg', verbose_name='pkg'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='mightiness',
            field=models.TextField(max_length=255, verbose_name='kinou'),
        ),
    ]
