# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0024_auto_20160518_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function_updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=255, verbose_name='sakuseisya')),
                ('content', models.CharField(max_length=255, verbose_name='kousinnnaiyou')),
                ('reason', models.CharField(max_length=255, verbose_name='kousinnriyuu')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_updateds', to='data_base.Function', verbose_name='function')),
            ],
        ),
        migrations.CreateModel(
            name='Proglam_updated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=255, verbose_name='sakuseisya')),
                ('content', models.CharField(max_length=255, verbose_name='kousinnnaiyou')),
                ('reason', models.CharField(max_length=255, verbose_name='kousinnriyuu')),
            ],
        ),
        migrations.AlterField(
            model_name='pkg_updated',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkg_updateds', to='data_base.Pkg', verbose_name='pkg'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglams', to='data_base.Pkg', verbose_name='pkg'),
        ),
        migrations.AddField(
            model_name='proglam_updated',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglam_updateds', to='data_base.Proglam', verbose_name='proglam'),
        ),
    ]
