# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_base', '0025_auto_20160518_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkg_updated',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pkg_updated',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pkg_updateds', to='data_base.Pkg', verbose_name='pkg'),
        ),
        migrations.AlterField(
            model_name='proglam',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proglams', to='data_base.Pkg', verbose_name='pkg'),
        ),
    ]
